CREATE TABLE inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL
);
CREATE TABLE transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    items TEXT NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    payment DECIMAL(10,2) NOT NULL,
    change_amount DECIMAL(10,2) NOT NULL,
    date_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
